### ISSUE TITLE
Any tracer with uridecodebin will cause a SIGSEGV

### ISSUE THREAD

**Issue by migueltaylor** [RidgeRun/gst-shark#82]
Pipeline:

```
GST_DEBUG="GST_TRACER:7" GST_TRACERS="interlatency" gst-launch-1.0 \
uridecodebin3 uri="rtspt://170.93.143.139/rtplive/1701519c02510075004d823633235daa" ! queue ! videorate max-rate=15 ! fakesink sync=true
```

Output (TX2):

```
0:00:00.073488590 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598ab8d80 (cpuusage)
0:00:00.073604269 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598ab8e40 (graphic)
0:00:00.073664717 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598ab8f00 (proctime)
0:00:00.073720236 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598cfa830 (interlatency)
0:00:00.073788876 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598cfa8f0 (scheduletime)
0:00:00.073844299 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598cfa9b0 (framerate)
0:00:00.073906443 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598cfaa70 (queuelevel)
0:00:00.073962986 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598cfab30 (bitrate)
0:00:00.074014858 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracer.c:164:gst_tracer_register:<registry0> update existing feature 0x5598cfabf0 (buffer)
0:00:00.074949570 12404   0x5598ceb690 TRACE             GST_TRACER gsttracerrecord.c:111:gst_tracer_record_build_format: interlatency.class, from_pad=(structure)"scope\,\ type\=\(type\)gchararray\,\ related-to\=\(GstTracerValueScope\)GST_TRACER_VALUE_SCOPE_PAD\;", to_pad=(structure)"scope\,\ type\=\(type\)gchararray\,\ related-to\=\(GstTracerValueScope\)GST_TRACER_VALUE_SCOPE_PAD\;", time=(structure)"scope\,\ type\=\(type\)gchararray\,\ related-to\=\(GstTracerValueScope\)GST_TRACER_VALUE_SCOPE_PROCESS\;";
0:00:00.075017538 12404   0x5598ceb690 DEBUG             GST_TRACER gsttracerrecord.c:125:gst_tracer_record_build_format: new format string: interlatency, from_pad=(string)%s, to_pad=(string)%s, time=(string)%s;
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtspt://170.93.143.139/rtplive/1701519c02510075004d823633235daa
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request
Caught SIGSEGV
#0  0x0000007f8dbe9048 in __GI___poll (fds=0x5598d3f9a0, nfds=547840025144, timeout=<optimized out>) at ../sysdeps/unix/sysv/linux/poll.c:41
#1  0x0000007f8dcf5e08 in  () at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#2  0x0000005598afcc90 in  ()
Spinning.  Please run 'gdb gst-launch-1.0 12404' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.

```

**Comment by michaelgruner** [comment]
Attending in #89
